=== cpilarski11/CS345-Database-Modeling-Final-Project/hockey.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- CS345 - Final Project
 Hockey Database
 Cameron Pilarski | Bob Doser -->

<!-- database declaration, at least one league, at least one venue -->
<!ELEMENT hockey (league)+, (venue)+>

<!-- each venue has a city, active status, and can have many games in a day -->
<!ELEMENT venue (name), (city), (activity), (games)+>
<!ATTLIST venue teamid ID #REQUIRED>

<!-- games have away and home team ID's, and game info such as time, date, scores -->
<!ELEMENT games (date), (time), (h_team), (a_team), (game_type), (h_score), (a_score)>

<!-- each league is composed of many teams -->
<!ELEMENT league ((name), (team)+, (activity))>

<!-- each team is composed of 1 owner, at least 1 coach, many players -->
<!ELEMENT team ((owner), (name), (city), (activity), (coach)+, (player)+, (awards)+, (records)+, (sponsors)+, (apparel)+, (affiliations)+)>
<!ATTLIST team teamid ID #REQUIRED>
<!ATTLIST team venue venue_name #REQUIRED>

<!-- a team can have multiple affiliate teams -->
<!ELEMENT affiliations (name), (city), (owner_name), (activity)>

<!-- a team could have apparel -->
<!ELEMENT apparel (name), (color)>

<!-- every team has records -->
<!ELEMENT records (year), (wins), (losses), (ties), (points), (place)>

<!-- a team could have more than one sponsor -->
<!ELEMENT sponsors (name), (year), (amount)>

<!-- owner -->
<!ELEMENT owner ((first), (last), (activity))>
<!ATTLIST owner ownerid ID #REQUIRED>

<!-- coach -->
<!ELEMENT coach ((first), (last), (type))>

<!-- a player can have statistics over multiple seasons, different types of equipment, and could have a salary  -->
<!ELEMENT player ((first), (last), (position), (handedness), (number), (activity), (statistics)+, (equipment)+, (salary)?)>
<!ATTLIST player playerid ID #REQUIRED>

<!-- equipment -->
<!ELEMENT equipment (equipment_type), (color)+>

<!-- salary -->
<!ELEMENT salary (amount), (years_remaining)>

<!-- team awards -->
<!ELEMENT awards ((name), (year), (description))>

<!-- stats -->
<!ELEMENT statistics ((year), (goals), (assists), (games_played), (points), (shots), (shooting_percentage), (pim), (saves)?, (gaa)?)>


<!-- attributes -->
<!ELEMENT first (#PCDATA) >

<!ELEMENT last (#PCDATA)>

<!ELEMENT activity EMPTY>
<!ATTLIST activity status(true|false) #REQUIRED>

<!ELEMENT city (#PCDATA)>

<!ELEMENT type EMPTY>
<!ATTLIST type role(Head|Assistant|Volunteer) #REQUIRED>

<!ELEMENT position EMPTY>
<!ATTLIST position playerPosition (C|LW|RW|D|G|LD|RD) #REQUIRED>

<!ELEMENT handedness EMPTY>
<!ATTLIST handedness hand (RH|LH|AM) #REQUIRED>

<!ELEMENT number (#PCDATA)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT year (#PCDATA)>

<!ELEMENT goals (#PCDATA)>

<!ELEMENT assists (#PCDATA)>

<!ELEMENT games_played (#PCDATA)>

<!ELEMENT points (#PCDATA)>

<!ELEMENT shots (#PCDATA)>

<!ELEMENT shooting_percentage (#PCDATA)>

<!ELEMENT pim (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT date (#PCDATA)>

<!ELEMENT time (#PCDATA)>

<!ELEMENT h_team EMPTY>
<!ATTLIST h_team teamid ID #REQUIRED>

<!ELEMENT a_team (#PCDATA)>
<!ATTLIST a_team teamid ID #REQUIRED>

<!ELEMENT game_type EMPTY>
<!ATTLIST game_type type (Final|Regular|Playoff|Friendly|Exhibition) #REQUIRED>

<!ELEMENT h_score (#PCDATA)>

<!ELEMENT a_score (#PCDATA)>

<!ELEMENT wins (#PCDATA)>

<!ELEMENT losses (#PCDATA)>

<!ELEMENT ties (#PCDATA)>

<!ELEMENT place (#PCDATA)>

<!ELEMENT amount (#PCDATA)>

<!ELEMENT saves (#PCDATA)>

<!ELEMENT gaa (#PCDATA)>

<!ELEMENT equipment_type EMPTY>
<!ATTLIST equipment_type type (Shoulder Pads|Helmet|Neckguard|Elbow Pads|Gloves|Stick|Pants|Shin Pads|Skates)>

<!ELEMENT years_remaining (#PCDATA)>

<!ELEMENT color EMPTY>
<!ATTLIST color color_type (Red|Yellow|Blue|Green|Orange|Purple|Black|White|Silver|Gold|Grey|Brown)>

<!ELEMENT owner_name (#PCDATA)>

=== cpilarski11/CS345-Database-Modeling-Final-Project/hockey.xml
<!DOCTYPE hockey SYSTEM "hockey.dtd">

<!-- CS345 - Final Project
 Hockey Database
 Cameron Pilarski | Bob Doser -->

<!-- Inserted some sample data -->
<!-- Sample data includes: 1 league, 1 team and its apparel,
 1 player and their statistics, equipment, team awards and
 records, 1 venue and its games, team affiliations -->

<!-- database -->
<hockey>
    <!-- league (NHL) -->
    <league>
        <name>National Hockey League</name>
        <team teamid="5hdyer4" venue="Hope Arena">

            <!-- team owner -->
            <owner ownerid="jj10945">
                <first>Jeremy</first>
                <last>Jacobs</last>
                <activity status="true"/>
            </owner>
            <!-- end team owner -->

            <name>Penguins</name>
            <city>Pittsburgh</city>
            <activity status="true"/>

            <!-- team coaches-->
            <coach>
                <first>Blake</first>
                <last>Tunnel</last>
                <type role="Head"/>
            </coach>
            <coach>
                <first>Mike</first>
                <last>Frost</last>
                <type role="Assistant"/>
            </coach>
            <!-- end team coaches -->

            <!-- player -->
            <player playerid="ds12452">
                <first>Dylan</first>
                <last>Smith</last>
                <position playerPosition="C"/>
                <handedness hand="RH"/>
                <number>11</number>
                <activity status="true"/>

                <!-- player staistics -->
                <statistics>
                    <year>2016</year>
                    <goals>34</goals>
                    <assists>12</assists>
                    <games_played>45</games_played>
                    <points>86</points>
                    <shots>134</shots>
                    <shooting_percentage>18.00</shooting_percentage>
                    <pim>35</pim>
                    <saves>n/a</saves>
                    <gaa>n/a</gaa>
                </statistics>
                <!-- end player statistics -->

                <!-- player equipment -->
                <equipment>
                    <equipment_type type="Helmet"/>
                    <color color_type="Black"/>
                </equipment>
                <equipment>
                    <equipment_type type="Stick"/>
                    <color color_type="Black"/>
                </equipment>
                <!-- end player equipment-->

                <!-- player salary-->
                <salary>
                    <amount>90000.00</amount>
                    <years_remaining>8</years_remaining>
                </salary>
                <!-- end player salary -->

            </player>
            <!-- end player -->

            <!-- team awards -->
            <awards>
                <name>Stanley Cup</name>
                <year>2016</year>
                <description>Championship title</description>
            </awards>
            <!-- end awards -->

            <!-- team records -->
            <records>
                <year>2016</year>
                <wins>44</wins>
                <losses>1</losses>
                <ties>0</ties>
                <points>88</points>
                <place>1</place>
            </records>
            <!-- end of team records -->

            <!-- team sponsors -->
            <sponsors>
                <name>Nokia</name>
                <year>2016</year>
                <amount>24000.00</amount>
            </sponsors>
            <!-- end team sponsors -->

            <!-- team apparel -->
            <apparel>
                <name>Short sleeve shirt</name>
                <color color_type="Black"/>
            </apparel>
            <!-- end team apparel -->

            <!-- team affiliations -->
            <affiliations>
                <name>Ducks</name>
                <city>Wolcott</city>
                <activity status="true"/>
                <owner_name>Robert Smith</owner_name>
            </affiliations>
            <!-- end team affiliations -->

        </team>
        <!-- end teaam -->

        <!-- league status -->
        <activity status="true"/>

    </league>
    <!-- end league (NHL) -->

    <!-- game venues -->
    <venue teamid="5hdyer4">
        <name>Hope Arena</name>
        <city>Pittsburgh</city>
        <activity status="true"/>

        <!-- team games -->
        <games>
            <date>2016-12-12</date>
            <time>16:00:00</time>
            <game_type type="Exhibition"/>
            <h_team teamid="5hdyer4"/>
            <a_team teamid="1jsgd56"/>
            <h_score>3</h_score>
            <a_score>1</a_score>
        </games>
        <!-- end team games -->

    </venue>
    <!-- end game venues -->

</hockey>
<!-- end of database -->
